---
- name: Install NodeJS
  apk:
    name: nodejs
    state: present
    update_cache: yes
- name: Install Yarn
  apk:
    name: yarn
    state: present
- name: Install The Lounge
  yarn:
    name: thelounge
    version: "{{ thelounge_version }}"
    global: yes
- name: Install Esprima for validation
  yarn:
    name: esprima
    state: latest
    global: yes

- name: Retrieve the location of the global `node_modules` directory
  shell: yarn global dir
  register: node_modules_path
  changed_when: no

- name: Ensure .thelounge_home points to the correct configuration directory
  copy:
    content: "{{ thelounge_home_path }}"
    dest: "{{ node_modules_path.stdout }}/node_modules/thelounge/.thelounge_home"